version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/qrestro_db
      - JWT_SECRET=mysecret
    ports:
      - "4000:4000"

volumes:
  mongo_data:
